In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# Problem 3

In [17]:
# Part a)
r0 = 0.03
N = 12
u = 0.0025
m = 0
d = -u
M = 1000

RN = np.zeros((M, N+1))
RN[:, 0] = r0

for i in range(M):
    for j in range(N):
        U = np.random.uniform(0, 1, N)
        RN[i, j+1] = r0+u*(stats.binom.ppf(U[j], N, 0.4))+ \
        m*(int(0.5*stats.binom.ppf(U[j], N, 0.4)))+d*(int(0.5*stats.binom.ppf(U[j], N, 0.4)))
    
print(RN)

[[0.03   0.0375 0.035  ... 0.0375 0.035  0.0375]
 [0.03   0.035  0.0325 ... 0.035  0.0375 0.035 ]
 [0.03   0.0425 0.04   ... 0.035  0.0325 0.0375]
 ...
 [0.03   0.04   0.0375 ... 0.035  0.0375 0.035 ]
 [0.03   0.0325 0.0375 ... 0.0375 0.0375 0.035 ]
 [0.03   0.04   0.035  ... 0.035  0.035  0.0425]]
